version: "3"

services:
  node:
    image: "node:12"
    container_name: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: "npm start"
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    container_name: "pg-db"
    restart: always
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    logging:
      driver: none
