version: "3"
services:
  node:
    image: "node:12"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: "npm start"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: kraken
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
